### ISSUE TITLE
Add API to customize the persistedLogFileURL of ARKLogStore's ARKDataArchive

### ISSUE THREAD

**Issue by zadr** [square/Aardvark#112]
In Aardvark 2, `persistedLogFileURL` was a public API on `ARKLogStore` which allowed subclasses to override things and redirect logs to a custom destination, e.g. outside of app support or to a subfolder of app support

In Aardvark 3, `persistedLogFileURL` was made internal to `ARKLogStore` which means that subclasses need to redeclare private properties and make a new `ARKDataArchive` in order to continue to redirect logs

It would be great if Aardvark had an initializer or other API that allowed for the log file path to be customized without the need to subclass things!

**Comment by NickEntin** [comment]
I think adding an initializer that specifies a full URL sounds reasonable. Adding to the list for CoreAardvark 3.0.
