### ISSUE TITLE
ARKLogMessage should probably be a protocol, not a base class 

### ISSUE THREAD

**Issue by rhgills** [square/Aardvark#35]
Raised this issue here: https://github.com/square/Aardvark/pull/34

**Comment by dfed** [comment]
Specifically, here: https://github.com/square/Aardvark/pull/34#discussion_r56731033

**Comment by rhgills** [comment]
Resolved offline - a protocol isn't really applicable here, as we couldn't come up with any reason why there would be multiple implementations of ARKLogMessage.
