### ISSUE TITLE
defaultLogStore should have a maximumLogMessageCount set

### ISSUE THREAD

**Issue by natan** [square/Aardvark#61]
Currently if you follow the README and use `Aardvark.addDefaultBugReportingGestureWithEmailBugReporter()` to setup Aardvark you will get an unlimited amount of logs stored to disk. After a while that adds up to a lot of disk and will cause issues. I think it'd be reasonable for `defaultLogStore` to have maximumLogMessageCount set to a reasonable value (5,000?) to prevent this.

**Comment by dfed** [comment]
Are you sure? [Creating the default log store](https://github.com/square/Aardvark/blob/master/CoreAardvark/ARKLogDistributor.m#L90) goes through the [initWithPersistedLogFileName](https://github.com/square/Aardvark/blob/master/CoreAardvark/ARKLogStore.m#L74) initializer, which has a `maximumLogMessageCount` of 2000. Or is there a bug somewhere?

**Comment by natan** [comment]
@dfed Huh, you're totally right. I debugged that incorrectly, sorry for the noise!
