### ISSUE TITLE
Decompose Aardvark into smaller modules

### ISSUE THREAD

**Issue by NickEntin** [square/Aardvark#85]
Aardvark currently has a lot of responsibilities - adding log messages, viewing those log messages in the app, generating data for a bug report, and sending that bug report via email. Breaking it down into smaller modules unlocks a couple of distinct advantages:

* **Support including only necessary portions of the bug reporting system based on build configuration.** In particular, consumers should be able to include the core parts of the bug reporting functionality (taking a screenshot, generating attachments, etc.) without including the mail dialogs. By modularizing the core components of generating a bug report, we can make it easier to generate more customizable bug reporting workflows, while still supporting the simple-setup case with the existing email bug reporter.
* **Improve extensibility for future additions.** In particular, I think there is a lot of power in being able to extend the variety of attachments that can be generated and included in a bug reported, as well as the ways in which that bug report can be shared.

The disadvantage comes in the form of a few extra sets in setting up the dependencies (since there are now more dependencies) and discoverability of new features (since they may be in a not-yet-imported module), but I think these are greatly outweighed by the advantages.

The current frameworks (Aardvark and CoreAardvark) will be broken down into four separate frameworks based on functionality. Frameworks related to the logging functionality with be prefixed with "CoreAardvark" (where `CoreAardvark` itself is the core logging framework) and frameworks related to the bug reporting functionality will be prefixed with "Aardvark" (where `Aardvark` itself is the core bug reporting framework). This gives us:

* **CoreAardvark** - Core log message distribution and storage functionality. This has no dependencies and can be run in app extensions (no change from the current framework).
* **CoreAardvarkLoggingUI** - User interfaces to view log messages inside an app.
* **Aardvark** - Core bug reporting functionality. This will include the informational pieces of bug reporting, such as generating a screenshot and view hierarchy description.
* **AardvarkMailUI** - User interfaces to submit a bug report via the Mail app.

This provides us with a solid foundation to build out new logging and bug reporting functionality in a modular fashion on top of the two core frameworks, CoreAardvark and Aardvark.

In the interest of making the addition of new bug reporting flows simpler, I think we should keep the bug report "attachment" concept in the main Aardvark framework. Since it isn't inherently tied to the mail concepts right now, the only change to the class will be a rename from `ARKEmailAttachment` to `ARKBugReportAttachment`.

We can then begin to add new modules over time, which will generally fall into one of the following categories for most cases:

* **Attachment vendors** - Frameworks that provide additional data that can be attached to a bug report.
* **Bug reporting workflows** - Frameworks that provide alternate ways to file a bug report. For example, #47 mentions using the Gmail SDK to provide an alternate mail client to the built-in mail dialog. This could be provided as an alternate bug reporter podspec that has a dependency on that SDK. Similarly, we could introduce new bug reporters that connect directly to various services' APIs, for instance to create a new issue on GitHub.

With this, the frameworks will be broken down into small components and restructured as follows:

| | Current | Proposed |
| :--- | :---: | :---: |
| Log methods (`Aardvark.log()`, `ARKLog()`, `ARKLogWithType()`) | CoreAardvark | CoreAardvark |
| Log message primitives (`ARKLogMessage`, `ARKLogType`) | CoreAardvark | CoreAardvark |
| Log storage (`ARKLogStore`, `ARKDataArchive`, file management utilities) | CoreAardvark | CoreAardvark |
| Log distribution (`ARKLogDistributor`, `ARKLogObserver`) | CoreAardvark | CoreAardvark |
| Exception logging (`ARKExceptionLogging`) | CoreAardvark | CoreAardvark |
| Log formatting (`ARKLogFormatter`, `ARKDefaultLogFormatter` | Aardvark | CoreAardvark |
| In-app log viewing (view controllers and sharing utilities) | Aardvark | CoreAardvarkLoggingUI |
| Screenshot logging (`ARKLogScreenshot()` and distributor additions) | Aardvark | Aardvark |
| Bug reporter protocol (`ARKBugReporter`) | Aardvark | Aardvark |
| Bug report attachments (`ARKBugReportAttachment`) | Aardvark | Aardvark |
| Convenience method to add (generic) bug reporter via gesture | Aardvark | Aardvark |
| Email bug reporter (`ARKEmailBugReporter`, `ARKEmailBugReportConfiguration`) | Aardvark | AardvarkMailUI |
| Convenience method to add email bug reporter via gesture | Aardvark | AardvarkMailUI |

**Comment by dfed** [comment]
Love this roadmap! Thanks for figuring out how to fix the original sin of this repo.

One thought: previously `Core` denoted that the module was extension safe. That won't be true after this change, but I think that that's okay.

**Comment by NickEntin** [comment]
That's a really good point. I suppose the logging vs. bug reporting distinction isn't totally clear either, since Aardvark also includes extensions for logging (i.e. the screenshot logging additions). Maybe `AardvarkLoggingUI` is a better name for the in-app log viewing module?

**Comment by dfed** [comment]
I like `AardvarkLoggingUI` 🙂

**Comment by NickEntin** [comment]
This was resolved through #86, #87, and #88.
